export const restaurant = [
  {
    id: 1,
    img1: 'images/FRAN.png',
    category: ['ranking', 'popular','a'],
    title: "Fran’s Brunch & Greens",
    desc: 'คาเฟ่, อาหารเช้า',
    rating: '5.0',
    review: 121,
  },
  {
    id: 2,
    img1: 'images/Wallflower.png',
    category: ['ranking', 'popular','a'],
    title: 'Wallflower Cafe',
    desc: 'คาเฟ่, บาร์',
    rating: '5.0',
    review: 90,
  },
  {
    id: 3,
    img1: 'images/Camelot.png',
    category: ['ranking', 'popular','a'],
    title: 'Camelot Cafe Bangkok',
    desc: 'คาเฟ่, อาหารฝรั่งเศส',
    rating: '5.0',
    review: 201,
  },
  {
    id: 4,
    img1: 'images/Scoopp-Homemade.png',
    category: ['popular','a'],
    title: 'Scoopp',
    desc: 'ไอศกรีมโฮมเมด, ขนมหวาน',
    rating: '5.0',
    review: 300,
  },
  {
    id: 5,
    img1: 'images/ginzado.png',
    category: ['popular','newres'],
    title: 'MeMo Paradise',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 6,
    img1: 'images/ginzado.png',
    category: ['popular','newres'],
    title: 'MoMo Paradise',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 7,
    img1: 'images/ginzado.png',
    category: ['newres'],
    title: 'hoho Paradise',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 8,
    img1: 'images/ginzado.png',
    category: ['newres'],
    title: 'jujue',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
];
