export const restaurant = [
  {
    id: 1,
    img1: '../images/FRAN.png',
    img2: '../images/FRAN2.png',
    img3: '../images/FRAN3.png',
    img4: '../images/FRAN4.png',
    category: ['ranking', 'popular', 'pop'],
    title: 'Fran’s Brunch & Greens',
    desc: 'คาเฟ่, อาหารเช้า',
    rating: '5.0',
    review: 121,
  },
  {
    id: 2,
    img1: '../images/Wallflower.png',
    category: ['ranking', 'popular', 'pop'],
    title: 'Wallflower Cafe',
    desc: 'คาเฟ่, บาร์',
    rating: '5.0',
    review: 90,
  },
  {
    id: 3,
    img1: '../images/Camelot.png',
    category: ['ranking', 'popular', 'pop'],
    title: 'Camelot Cafe Bangkok',
    desc: 'คาเฟ่, อาหารฝรั่งเศส',
    rating: '5.0',
    review: 201,
  },
  {
    id: 4,
    img1: '../images/Scoopp-Homemade.png',
    category: ['popular', 'pop'],
    title: 'Scoopp',
    desc: 'ไอศกรีมโฮมเมด, ขนมหวาน',
    rating: '5.0',
    review: 300,
  },
  {
    id: 5,
    img1: '../images/stockroom1.png',
    category: ['popular', 'newres', 'new'],
    title: 'StockRoom',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 6,
    img1: '../images/earlymatcha1.png',
    category: ['popular', 'newres', 'new'],
    title: 'Ealily Matcha House เอกมัย',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 7,
    img1: '../images/Have A Nice Day1.png',
    category: ['newres', 'new'],
    title: 'Have A Nice Day Tea House & Bar',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 8,
    img1: '../images/Home Work Cafe1.png',
    category: ['newres', 'new'],
    title: 'Home Work Cafe สุขุมวิท 31',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 9,
    img1: '../images/Ports Coffee1.png',
    category: ['newres'],
    title: 'Ports Coffee',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 10,
    img1: '../images/One Two Two Coffee Bar1.png',
    category: ['popular', 'newres'],
    title: 'One Two Two Coffee Bar',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 11,
    img1: '../images/Teyaki1.png',
    category: ['popular', 'newres'],
    title: 'Teyaki',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 12,
    img1: 'images/Nosleep1.png',
    category: ['popular', 'newres'],
    title: 'Nosleep bkk',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
];
