export const restaurant = [
  {
    id: 1,
    img1: '../images/FRAN.png',
    img2: 'images/Fran1.png',
    img3: 'images/FRAN2.png',
    img4: 'images/FRAN4.png',
    img2: '../images/FRAN2.png',
    img3: '../images/FRAN3.png',
    img4: '../images/FRAN4.png',
    rate: '../images/rating.png',
    category: ['ranking', 'popular', 'pop'],
    title: 'Fran’s Brunch & Greens',
    desc: 'คาเฟ่, อาหารเช้า',
    open: '8.00 - 18.00 น',
    location:' 64 ซอย งามดูพลี แขวง ทุ่งมหาเมฆ เขต สาทร กรุงเทพมหานคร 10120 ประเทศไทย กรุงเทพมหานคร ',
    budget:'500 - 1,000 บาท',
    line:'@frans.bkk',
    facebook:' https://www.facebook.com/Frans.bangkok/ ',
    ig:'https://www.instagram.com/frans.bkk/',
    map:'https://goo.gl/maps/CA7tZRVZaAmLWKe89',
    comment:['ร้านนี้ครั้งเดียวพอจ้า บ้งมากเรื่องพนักงาน รู้สึกอึดอัดและแย่มาก ทั้งที่อาหารโอเคนะ แต่อย่างที่บอกต่อให้อาหารโอเค แต่ไม่ซ้ำแน่นอน',
  'รีวิวยิ่งใหญ่มาก แต่พอไปจริง คือ ผิดหวังสุดๆ และ เป็นหลายแบรนด์กับเจ้าของคนนี้ เน้น Fad ไม่ต้องค่อยเน้น long term คนรีวิวให้ได้ตรงปกติ แต่คนดูตามไปกิน ไม่ตรงปก เสียหายหลายกลุ่มเลยนะ',
'กระแสมาทางลบเรื่อยๆ ตั้งแต่วันร้านเปิด และมาแนวเดียวกันหมดเลย ทางร้านต้องคิดแล้วล่ะ รีบแก้ไขเถอะ','ราคาพอๆกับตอนไปนั่งกินอยู่อเมริกา แต่อาหารกับบริการคือบ่ได้เลย ผู้บริหารควรออกมาเทคแอคชั่นเพื่อปรับปรุงได้แล้วนะ ส่วนใหญ่ที่เห็นยังมีลูกค้าคือรีวิวอวยกันสุด กับน่าไปถ่ายรูป แต่ก็นั่นแหละ ครั้งเดียวจบ ไม่ซ้ำแน่นอน'],
    rating: '5.0',
    review: 121,
  },
  {
    id: 2,
    img1: 'images/Wallflower.png',
    category: ['ranking', 'popular','pop'],
    title: 'Wallflower Cafe',
    desc: 'คาเฟ่, บาร์',
    open: '11:00-00:00 น',
    location:' ซอยนานา สามารถเดินจากเยาวราชไปได้ ',
    budget:'300 - 1,000 บาท',
    line:'@frans.bkk',
    facebook:' https://www.facebook.com/wallflowerscafe.th/ ',
    ig:' https://www.instagram.com/wallflowerscafe.th',
    map:'https://goo.gl/maps/ABvWzHjV75BYpW9M6',
    comment:['พนักงานผู้ชาย พูดไม่สุภาพและแสดงกริยาหยาบคายกับลูกค้า เพียงเพราะลูกค้าเดินลงมาจ่ายเงินข้างล่าง และไม่ได้จ่ายที่โต๊ะเพราะไม่รู้ ไม่มีใครเดินมารับเงินเงิน พอถามกลับก็ตอบไม่สุภาพ และชักสีหน้าไม่พอใจใส่',
  'อาหาร​ เครื่องดื่มค่อนไปทางแพง​  สถานที่อึดอัดนะคะ​ พนักงานบริการดีมาก​ รวมๆแล้ว​ ไม่เหมาะกับคนไทยหรือวัยรุ่นเท่าไหร่',
'รสชาติกับราคาไม่สอดคล้องกันอย่างรุนแรง มาสามคนขอแก้วเพิ่มอีกใบ ให้ไม่ได้ค่ะ เพราะมันเป็นเซ็ต ไม่มี service mind คือยังไงมาสามคนต้องสั่งสองเซ็ตหรอคะถึงจะได้กินช่วงโควิดแบบนี้ต้องกินชาแก้วเดียวกัน จะฟ้องสาธารณสุข!!!!',
'ร้านสวย แต่พนักงานผู้หญิงคือโครตแย่ ไม่เต็มใจบริการก็นอนอยู่บ้านค่ะ ไม่ต้องทำงาน มองลูกค้าเหมือนมาขอกินฟรี ถ้ารับพรักงานแบบนี้มาบริการลูกค้าระวังเจ๊ง'],
    rating: '5.0',
    review: 90,
  },
  {
    id: 3,
    img1: 'images/Camelot.png',
    category: ['ranking', 'popular','pop'],
    title: 'Camelot Cafe Bangkok',
    desc: 'คาเฟ่, อาหารฝรั่งเศส',
    open: '10:00-22:00 น.',
    location:' ซอยเจริญกรุง 45 (ฝั่งตรงข้ามไปรษณีย์กลาง) ',
    budget:'300 - 1,000 บาท',
    line:'-',
    facebook:' https://www.facebook.com/CamelotCafe/?locale=th_TH ',
    ig:' https://www.instagram.com/camelotcafebangkok/',
    map:' https://maps.app.goo.gl/pKL8oUmsGs7DC1jc6?g_st=ic',
    comment:['ขออนุญาตรีวิวตามจริงนะคะ ไปมาวันนี้ เท่าที่สั่งกินมีอร่อยอยู่ไม่กี่อย่าง ตั้งแต่เข้าร้าน ไม่มีใครมารับออเดอร์ ตอนเข้าครั้งแรกพี่เจ้าของร้านเดินมาจัดโต๊ะให้อยู่นิดนึง จากนั้นไม่มีไรเลย รอของนานมาก',
  'ขอรีวิวจากที่วันนี้ลองไปมาค่ะ ร้านไม่มีระบบเลยค่ะ ตัวร้านสวยดี แต่บริการแย่มาก เราสั่งเครื่องดื่ม6แก้ว ขนมอีก2อย่าง แต่ทำนานเกือบ2ชั่วโมง แล้วร้านยังลืมออเดอร์ด้วย (ลืมน้ำส้มกับฮันนี่โทส) พอถามเรื่องออเดอร์ที่สั่งไป ร้านบอกว่าไม่มีส้มแล้ว แต่ทำน้ำอะไรมาให้ก็ไม่รู้ที่ไม่ใช่ส้ม'],
    rating: '5.0',
    review: 201,
  },
  {
    id: 4,
    img1: 'images/Scoopp-Homemade.png',
    category: ['popular','pop'],
    title: 'Scoopp',
    desc: 'ไอศกรีมโฮมเมด, ขนมหวาน',
    rating: '5.0',
    review: 300,
  },
  {
    id: 5,
    img1: '../images/stockroom1.png',
    category: ['popular', 'newres', 'new'],
    title: 'StockRoom',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 6,
    img1: '../images/earlymatcha1.png',
    category: ['popular', 'newres', 'new'],
    title: 'Ealily Matcha House เอกมัย',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 7,
    img1: '../images/Have A Nice Day1.png',
    category: ['newres', 'new'],
    title: 'Have A Nice Day Tea House & Bar',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 8,
    img1: '../images/Home Work Cafe1.png',
    category: ['newres', 'new'],
    title: 'Home Work Cafe สุขุมวิท 31',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 9,
    img1: '../images/Ports Coffee1.png',
    category: ['newres'],
    title: 'Ports Coffee',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 10,
    img1: '../images/One Two Two Coffee Bar1.png',
    category: ['popular', 'newres'],
    title: 'One Two Two Coffee Bar',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 11,
    img1: '../images/Teyaki1.png',
    category: ['popular', 'newres'],
    title: 'Teyaki',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
  {
    id: 12,
    img1: 'images/Nosleep1.png',
    category: ['popular', 'newres'],
    title: 'Nosleep bkk',
    desc: 'บุฟเฟต์ ,อาหารญี่ปุ่น',
    rating: '5.0',
    review: 300,
  },
];
